echo

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,5 +1,4 @@
-name: First test
-
+name: Pull Request Validation
 
 on:
   pull_request:
@@ -7,21 +6,41 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
+
   validate:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-
-      - name: Extract branch name
+      -name: Just pring
         shell: bash
-        run: echo running on branch ${GITHUB_REF##*/}
+        run: |
+          echo ${BASE_BRANCH}
+          echo ${{ github.event.pull_request.title }}
+      - name: Validating branch name
+        shell: bash
+        run: | 
+          echo Testing branch name: ${GITHUB_REF##*/}
+
+          project1="SWISCO-"
+          project2="SWISCA-"
+          ticket_number="([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])"
+          if [[ ! "${GITHUB_REF##*/}" =~ $project1$ticket_number && ! "${GITHUB_REF##*/}" =~ $project2$ticket_number ]]; then
+            echo "Branch name should contain JIRA ticket, like..."
+            echo " SWISCO-1234-short-description"
+            echo " feature/SWISCO-1234-short-description"
+            echo " release/SWISCA-1234-short-description"
+            exit 1
+          fi
+      - name: Validating title
+        shell: bash
+        run: | 
+          echo Testing title: ${{ github.event.pull_request.title }}
+      - name: force-fail
+        shell: bash
+        run: | 
+          echo Force fail
+          if [[ 1 == 1 ]]; then
+            echo "Force fail"
+            exit 1
+          fi
