fail

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -29,3 +29,11 @@ jobs:
             echo "Branch name should contain JIRA ticket."
             exit 1
           fi
+      - name: force-fail
+        shell: bash
+        run: | 
+          echo Force fail
+          if [[ 1 == 1 ]]; then
+            echo "Force fail"
+            exit 1
+          fi
